#!/usr/bin/env bash
#
# Tidy both worktrees for sharing. Dry run by default.
#
#   bash organize_repo.sh            # show what it would do
#   bash organize_repo.sh --apply
#
set -uo pipefail
APPLY=${1:-}
run() { if [ "$APPLY" = "--apply" ]; then eval "$@"; else echo "  would: $*"; fi }

# ---------------------------------------------------------------- irregular
echo "=== ~/maritime-irregular (primary) ==="
cd ~/maritime-irregular || exit 1

for d in assets benchmarks notebooks scripts slurm results docs; do
  run "mkdir -p $d"
done

# build artefacts and caches should never be tracked
run "git rm -r --cached vtp.egg-info 2>/dev/null || true"
run "rm -rf vtp.egg-info .ipynb_checkpoints"

# fixed-interval leftovers that arrived via merges
for f in slurm/train_gcvtp.slurm slurm/train_smoke.slurm slurm/test_env.slurm; do
  [ -f "$f" ] && run "git rm -f $f"
done

# demo gif for the README
if [ -f prediction_3272.gif ] && [ ! -f assets/prediction.gif ]; then
  run "cp prediction_3272.gif assets/prediction.gif"
fi

run "mv *.ipynb notebooks/ 2>/dev/null || true"
run "mv plot_history.py scripts/ 2>/dev/null || true"

cat > /tmp/.gitignore.irr <<'GI'
__pycache__/
*.pyc
*.egg-info/
build/
dist/
.ipynb_checkpoints/

venv/
data/
cache/
checkpoints/
logs/
results/*.json

# figures are regenerated by vtp.viz; the README demo is the exception
*.gif
*.png
!assets/*.gif
!assets/*.png

# benchmark sets are small and worth sharing -- keep them tracked
!benchmarks/*.npz

.DS_Store
GI
run "cp /tmp/.gitignore.irr .gitignore"

# --------------------------------------------------------------------- main
echo
echo "=== ~/maritime (comparison arm) ==="
cd ~/maritime || exit 1

for d in assets notebooks scripts slurm results; do
  run "mkdir -p $d"
done
run "rm -rf .ipynb_checkpoints"
run "mv *.ipynb notebooks/ 2>/dev/null || true"
for f in debug_batching.py debug_training.py; do
  [ -f "$f" ] && run "git rm -f $f"     # served their purpose; git history keeps them
done
run "mv sweep.py analyze_sweeps.py scripts/ 2>/dev/null || true"

cat > /tmp/.gitignore.main <<'GI'
__pycache__/
*.pyc
.ipynb_checkpoints/

venv/
data/
cache/
checkpoints/
logs/

*.gif
*.png
!assets/*.gif
!assets/*.png

.DS_Store
GI
run "cp /tmp/.gitignore.main .gitignore"

echo
echo "=== not automated ==="
cat <<'NOTE'
  1. Save the two README.md files and PROJECT_STATUS.md into their branches.
  2. GitHub -> Settings -> Branches -> default branch = irregular-sampling
     so visitors land on the primary model.
  3. Check the demo gif renders and is under ~5 MB:
        ls -lh assets/prediction.gif
  4. Commit each worktree separately:
        cd ~/maritime-irregular && git add -A && git commit -m "..." && git push
        cd ~/maritime           && git add -A && git commit -m "..." && git push
  5. Sanity check before sharing:
        cd ~/maritime-irregular && source venv/bin/activate
        python3 -c "from vtp.benchmark import BenchmarkSet, default_baselines; print('ok')"
NOTE
